# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 850))
        MainWindow.setMaximumSize(QtCore.QSize(1300, 850))
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 50, 931, 731))
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setObjectName("label")
        self.push = QtWidgets.QPushButton(self.widget)
        self.push.setGeometry(QtCore.QRect(970, 50, 311, 61))
        self.push.setObjectName("push")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(970, 200, 311, 81))
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.push2 = QtWidgets.QPushButton(self.widget)
        self.push2.setGeometry(QtCore.QRect(970, 120, 311, 61))
        self.push2.setObjectName("push2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(970, 300, 311, 81))
        self.label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(970, 400, 311, 81))
        self.label_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.plaka_liste = QtWidgets.QLabel(self.widget)
        self.plaka_liste.setGeometry(QtCore.QRect(970, 500, 311, 281))
        self.plaka_liste.setFrameShape(QtWidgets.QFrame.Box)
        self.plaka_liste.setText("")
        self.plaka_liste.setObjectName("plaka_liste")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 790, 160, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.fps = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.fps.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fps.setFont(font)
        self.fps.setFrameShape(QtWidgets.QFrame.Box)
        self.fps.setText("")
        self.fps.setObjectName("fps")
        self.horizontalLayout.addWidget(self.fps)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.widget)

        self.retranslateUi(MainWindow)
        self.push.clicked.connect(MainWindow.kamera_ac) # type: ignore
        self.push2.clicked.connect(MainWindow.kamera_kapat) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.push.setText(_translate("MainWindow", "KAMERAYI AÇ "))
        self.push2.setText(_translate("MainWindow", "KAMERAYI KAPAT"))
        self.label_5.setText(_translate("MainWindow", "FPS :"))
        self.label_6.setText(_translate("MainWindow", "KAMERA GÖRÜNTÜSÜ "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
